### ISSUE TITLE
Release 2016.01.21.1945 does not start and cannot be reinstalled

### ISSUE THREAD

**Issue by rneuber1** [erdomke/InnovatorAdmin#138]
After updating to 2016.01.21.1945, InnovatorAdmin does not start.
Reinstalling is not possible:
![image](https://cloud.githubusercontent.com/assets/6908002/12506109/d03efffc-c0ec-11e5-933f-8b621fda7353.png)

But "Open Setup.log" does nothing...

**Comment by rneuber1** [comment]
Building from source works...

**Comment by erdomke** [comment]
I updated the Squirrel.Windows package which is used for the update and install in the hopes that it might help somehow with your update and install woes.  I will also try an install on other computers here to see if I can understand what is going on.  However, the other bug is now fixed in the latest release

**Comment by rneuber1** [comment]
It still does not work. A Process "InnovatorAdmin.vshost.exe" appears in task manager an no matter how often I kill it, it reappears.

![image](https://cloud.githubusercontent.com/assets/6908002/12513224/f0187d14-c11c-11e5-968d-39e86f5ef9d1.png)

**Comment by erdomke** [comment]
The *.vshost.exe process is from Visual Studio.  If you shut down the InnovatorAdmin project in Visual studio, that should go away.  The install problems should be separate...

**Comment by rneuber1** [comment]
Using ProcessExplorer I found that the process above was called from sh.exe which I then successfully killed.
A subsequent install gives the "Installation failed" message, again.

Another observation: Does setup.exe delete itself? 
Write me an email if you are interested in a WebEx session now to have look at my system.

**Comment by erdomke** [comment]
Embarrassingly, I can't seem to find your e-mail.  Connect on slack?
